id: P009517
initial_creation_type: ocr
source_metadata:
  id: bdr:W19664
  title: གནམ་ཆོས་རྫོགས་ཆེན་སངས་རྒྱས་ལག་འཆང་གི་སྔོན་འགྲོའི་ཁྲིད་ཡིག་བདེ་ཆེན་ལམ་བཟང་།
  author: ''
  volumes:
    7cf1fbbf9e6342c398d1c926f9f82688:
      image_group_id: I1547
      title: ''
      volume_number: 1
      total_pages: 318
      base_file: v001.txt
