id: I14F822F8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:18:24+00:00'
last_modified: '2022-06-08T11:35:29.313629+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19664
  title: གནམ་ཆོས་རྫོགས་ཆེན་སངས་རྒྱས་ལག་འཆང་གི་སྔོན་འགྲོའི་ཁྲིད་ཡིག་བདེ་ཆེན་ལམ་བཟང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5454':
      image_group_id: I1547
      title: ''
      total_pages: 318
      order: 1
      base_file: 5454.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
